#!/bin/sh

echo "Rodando validações..."

if command -v cmd >/dev/null 2>&1; then
    WIN_PATH=$(cygpath -w "$(pwd)/scripts/check.bat")
    cmd /c "$WIN_PATH" || { echo "Erro! Commit cancelado."; exit 1; }
else
    make check || { echo "Erro! Commit cancelado."; exit 1; }
fi

echo "Tudo certo!"
