#!/bin/sh

echo "Rodando validações..."

if command -v cmd >/dev/null 2>&1; then
    cmd /c scripts\\check.bat
else
    make check
fi

if [ $? -ne 0 ]; then
  echo "Erro! Commit cancelado."
  exit 1
fi

echo "Tudo certo!"
